### ISSUE TITLE
Json and groovy file issue

### ISSUE THREAD

**Issue by himanshush13** [pacroy/abap-rest-api#3]
Hello @pacroy 

We are following your blog (Continuous Integration in ABAP using Jenkins) and the way you have explained is very nice. We are looking forward to do the CI/CD process first by using ECC system and github, according to your blog.
We have a linux vm with jenkins.
We installed ABAPGIT and it is working fine.
We cloned your repository and there we are facing issues,
with json and jenkinsfile,
We have updated the files with the details simply, but still facing the same issue on every change.

![image](https://user-images.githubusercontent.com/36809136/72984569-043e2c80-3e0a-11ea-8b79-1456316856d0.png)

Please help us out.
Warm Regards

**Comment by pacroy** [comment]
Have you tested your link that it returns JSON, not HTML page?

https://github.com/testabapdevops/pacroypipeline/blob/master/abap_unit_coverage.postman_collection.json seems to return an HTML page. You may need to use [the raw link](https://raw.githubusercontent.com/testabapdevops/pacroypipeline/master/abap_unit_coverage.postman_collection.json).

**Comment by ghost** [comment]
Thank you @pacroy  for the correction, but we are still so far to achieve this.

![image](https://user-images.githubusercontent.com/58258996/73175722-d4a46280-4130-11ea-9a38-de833a7c6d57.png)

still facing some connection issues.
